# Auto-NVM Zsh Integration
# This file is automatically generated by `auto-nvm setup`
# It provides automatic Node.js version switching when changing directories

# Save original cd function
__auto_nvm_original_cd() {
    builtin cd "$@"
}

# Override cd to trigger auto-nvm on directory change
cd() {
    __auto_nvm_original_cd "$@" || return

    # Run auto-nvm switch to check for .nvmrc
    local nvm_output
    nvm_output=$(auto-nvm --quiet switch --print 2>/dev/null)
    if [ -n "$nvm_output" ]; then
        eval "$(auto-nvm --quiet switch)"
    fi
}

# Startup check function
__auto_nvm_startup_check() {
    # Only run once per session
    if [[ -z "$__AUTO_NVM_STARTUP_CHECKED" ]]; then
        export __AUTO_NVM_STARTUP_CHECKED=1

        # Check for .nvmrc in current directory and switch if found
        local nvm_output
        nvm_output=$(auto-nvm --quiet switch --print 2>/dev/null)
        if [[ -n "$nvm_output" ]]; then
            eval "$(auto-nvm --quiet switch 2>/dev/null)" || true
        fi
    fi
}

# Run startup check
__auto_nvm_startup_check
