# Auto-NVM Bash Integration
# This file is automatically generated by `auto-nvm setup`
# It provides automatic Node.js version switching when changing directories

# Save original cd function
__auto_nvm_original_cd() {
    builtin cd "$@"
}

# Override cd to trigger auto-nvm on directory change
cd() {
    __auto_nvm_original_cd "$@" || return

    # Run auto-nvm switch to check for .nvmrc
    if [ -n "$(auto-nvm switch --print 2>/dev/null)" ]; then
        eval "$(auto-nvm switch)"
    fi
}
