# Auto-NVM PowerShell Integration Module
# This file is automatically generated by `auto-nvm setup`
# It provides automatic Node.js version switching when changing directories

# Save original Set-Location function
$script:__auto_nvm_original_SetLocation = ${function:Set-Location}

# Override Set-Location to trigger auto-nvm on directory change
function Set-Location {
    # Call original Set-Location
    & $script:__auto_nvm_original_SetLocation @PSBoundParameters

    # Run auto-nvm switch to check for .nvmrc
    $nvmOutput = auto-nvm --quiet switch --print 2>$null
    if ($nvmOutput) {
        Invoke-Expression (auto-nvm --quiet switch)
    }
}

# Startup check function
function Invoke-AutoNvmStartupCheck {
    # Only run once per session
    if (-not $global:__AUTO_NVM_STARTUP_CHECKED) {
        $global:__AUTO_NVM_STARTUP_CHECKED = $true

        # Check for .nvmrc in current directory and switch if found
        try {
            $nvmOutput = auto-nvm --quiet switch --print 2>$null
            if ($nvmOutput) {
                Invoke-Expression (auto-nvm --quiet switch 2>$null)
            }
        }
        catch {
            # Silently ignore errors during startup
        }
    }
}

# Run startup check
Invoke-AutoNvmStartupCheck
