# Auto-NVM PowerShell Integration Module
# This file is automatically generated by `auto-nvm setup`
# It provides automatic Node.js version switching when changing directories

# Save original Set-Location function
$script:__auto_nvm_original_SetLocation = ${function:Set-Location}

# Override Set-Location to trigger auto-nvm on directory change
function Set-Location {
    # Call original Set-Location
    & $script:__auto_nvm_original_SetLocation @PSBoundParameters

    # Run auto-nvm switch to check for .nvmrc
    $nvmOutput = auto-nvm switch --print 2>$null
    if ($nvmOutput) {
        Invoke-Expression (auto-nvm switch)
    }
}
