# Auto-NVM Fish Integration
# This file is automatically generated by `auto-nvm setup`
# It provides automatic Node.js version switching when changing directories

# Override cd function to trigger auto-nvm on directory change
function cd --description 'Change directory and run auto-nvm'
    builtin cd $argv

    # Run auto-nvm switch to check for .nvmrc
    set -l nvm_output (auto-nvm switch --print 2>/dev/null)
    if test -n "$nvm_output"
        eval (auto-nvm switch)
    end
end
