# Auto-NVM Fish Integration
# This file is automatically generated by `auto-nvm setup`
# It provides automatic Node.js version switching when changing directories

# Override cd function to trigger auto-nvm on directory change
function cd --description 'Change directory and run auto-nvm'
    builtin cd $argv

    # Run auto-nvm switch to check for .nvmrc
    set -l nvm_output (auto-nvm --quiet switch --print 2>/dev/null)
    if test -n "$nvm_output"
        eval (auto-nvm --quiet switch)
    end
end

# Startup check function
function __auto_nvm_startup_check
    # Only run once per session
    if not set -q __AUTO_NVM_STARTUP_CHECKED
        set -g __AUTO_NVM_STARTUP_CHECKED 1

        # Check for .nvmrc in current directory and switch if found
        set -l nvm_output (auto-nvm --quiet switch --print 2>/dev/null)
        if test -n "$nvm_output"
            eval (auto-nvm --quiet switch 2>/dev/null); or true
        end
    end
end

# Run startup check
__auto_nvm_startup_check
